version: '3'
services:




  wordpress:
    depends_on:
      - db
    image: wordpress
    restart: always
    volumes:
      - wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db      
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: mowazi
    ports:
      - 8000:80
    networks:
      - wp-network


  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
      - ./schema/:/docker-entrypoint-initdb.d 
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mowazi
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - wp-network


  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - wp-network




networks:
  wp-network:
volumes:
  db_data:
  wp_data:
